name = "sinapanel"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# اطلاعات دیتابیس D1 خود را در این بخش قرار دهید:
[[d1_databases]]
binding = "APP_DB"
database_name = "databased1"
database_id = "اینجا_آیدی_دیتابیس_خودت_رو_بذار"

# متغیرهای محیطی (اختیاری):
# [vars]
# PASSWORD = "123456"