name = "app-panel"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# دیتابیس KV برای ذخیره کاربران، حجم و جلسات آنلاین
[[kv_namespaces]]
binding = "APP_KV"
id = "YOUR_KV_NAMESPACE_ID_HERE"